version: "3.8"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # On expose nginx 80 sur localhost:3000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge